version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ port
      - "15672:15672"    # RabbitMQ Management UI port
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: ./numberproducer
    container_name: producer-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - FILE_STORAGE_PATH=/data/data.csv
    volumes:
      - ${PRODUCER_PATH}:/data
    networks:
      - app-network

  consumer:
    build:
      context: ./numberconsumer
    container_name: consumer-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - FILE_STORAGE_PATH=/data/data.csv
    volumes:
      - ${CONSUMER_PATH}:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge